### ISSUE TITLE
flake8 doesn't support [tool.flake8]

### ISSUE THREAD

**Issue by jelmer** [abravalheri/ini2toml#72]
flake8 doesn't support pyproject.toml yet - see https://github.com/PyCQA/flake8/issues/234

Not sure if it fits with the project, but it'd be great to be able to generate either a minimal setup.cfg with things that can't be migrate or to e.g. populate a .flake8 or tox.ini file with the flake8 settings. Or if those aren't an option, warn the user that part of their config won't be effective.

**Comment by abravalheri** [comment]
Hi @jelmer, currently this tool will use a "best effort guess" when it comes up with a section it does not have a plugin for. This is kind of intended because the project primary use is `setup.cfg` but it is not restricted to it.

That is why the docs recommend the user to review the configuration before using it.

We can add something in the logs every time that the "best effort guess" is used. I will have a look on this when I have some time. If any other member of the community would like to give it a go, PRs are also welcomed.

**Comment by jelmer** [comment]
Yeah, I appreciate that. Even with that in mind though, it'd be great for the tool to provide a hint to the user.

**Comment by abravalheri** [comment]
@jelmer in #76 I am giving my best shot, given the circumstances (and trying to avoid breaking the downstream users' test suite with strict warning filters).
